### ISSUE TITLE
Fix "method" parameter of SystemOfEquations.solve method

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#11]
The "solve" method of SystemOfEquations takes a "method" parameter, but does not use it when it calls solve_ivp.

**Comment by WalJT** [comment]
I've commented out the parameter and everything seems to still work...

**Comment by mjancen** [comment]
I've checked in the fix that I had in mind for this issue (commit bf03ea276b44a47b019a2a06fbe6e6784f8bd024) into the dev branch. @WalJT you should merge the pull the repo and merge the dev branch into ui_experimental before doing anymore work on that branch.
