### ISSUE TITLE
"params" parameter of SystemOfEquations constructor should probably not have a default value

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#12]
Right now, the "param" parameter to the SystemOfEquations constructor has a default value of None. A few points on this. I don't think that this parameter should have a default value - the params passed to the system should be explicit.

The reason why I think this is that, most likely, the SystemOfEquations object will only ever be called from the GUI code, which will always pass a dictionary, empty or otherwise, as the params argument. The nil case of an empty dictionary is already handled: no equation parameters are set.

Furthermore, the case of param=None is not handled in the code - if no parameter argument is passed to the constructor, then an exception will be thrown when the equation params are set.

I see no good reason to retain the default argument, param=None, for this parameter.

This is probably just a minor issue, but any thoughts are appreciated.

**Comment by WalJT** [comment]
I've removed the default value from equations.py in the ui_experimental branch.

**Comment by mjancen** [comment]
I have cherry-picked this fix onto the dev branch (commit 5a92e2db886b3d73f2fce3ffdae8831d35771090). Simple fix, gonna close this issue.
