### ISSUE TITLE
Discussion of project status

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#14]
Points to consider:

- Should we make a development release soon?
- Should we switch to testing and refining what we have soon?
- What is our release strategy?

**Comment by m-squared96** [comment]
In my opinion, we should decide on the required features we need to have a very basic but functional version of PyPLANE. PhaseSpacePlotter working properly, integrated into the GUI, etc. Perhaps not things like nullcline handlers *yet*,  just basic phase space visualisation. We can then perform some basic testing and release an alpha version. Perhaps then we can start making some noise about what we're doing in the relevant subreddits and so forth at this stage.
As for our long term release strategy I don't know.
