### ISSUE TITLE
Refactor code to utilise Python type hints

### ISSUE THREAD

**Issue by m-squared96** [m-squared96/PyPLANE#15]
As Maksim suggested, we should think about using Python type hints, a feature available in Python 3.5+ (https://www.python.org/dev/peps/pep-0484/). If nothing else, they will serve as a reminder to what each bit of the codebase does in the future if we ever decide to maintain this project long-term or use bits of it for other projects.

**Comment by WalJT** [comment]
All the GUI code uses hints now... I haven't touched the core code yet though.

**Comment by m-squared96** [comment]
I think this has pretty much been sorted and can be closed
