### ISSUE TITLE
PhasePlotter axis limits update when a trajectory is plotted

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#2]
When a trajectory is plotted by PhasePlotter, and if the trajectory is not contained in the current axis limits, the plot updates its limits in order to contain the new trajectory.

![pyplane_plotter_axis_lims_issue](https://user-images.githubusercontent.com/40291100/58624877-227a7980-82c9-11e9-9a1e-e0b2ce26ac48.png)

It would be better (or would it?) if the axis limits stayed constant even if the trajectory goes outside of the limits.

**Comment by m-squared96** [comment]
Fixed with a simple self.ax.set_xlim() and set_ylim() statement.

**Comment by mjancen** [comment]
This issue seems to have cropped up again in the ui_experimental branch. The set_xlim and set_ylim commands are there but the lims rescale nonetheless.

**Comment by mjancen** [comment]
Issue is resolved in fix_update_system branch (#24 ).
