### ISSUE TITLE
Look into removing __init__.py files

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#26]
Are these files necessary for our code?

**Comment by WalJT** [comment]
The `__init__.py` file in the PyPLANE directory marks it as a package so that it can be installed using `python setup.py install`. This is a necessary step in building a Snap package, and the file must remain, so I'd say we can close this issue.

**Comment by m-squared96** [comment]
As per @WalJT 's comment I'm going to close this issue as the file appears to be necessary
