### ISSUE TITLE
Store default values of code settings in a separate file

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#27]
Similar to ui_default_canvas.py, the default settings for a lot of other variables throughout the code should be contained in a separate file. This will aid in centralising our commonly used application settings that we, and the user potentially, often use. Thoughts?

**Comment by mjancen** [comment]
https://github.com/m-squared96/PyPLANE/blob/48d897c63f52730e6946fba4ef2b5db9b0149da2/source/defaults.py#L58 here there is `axes_limits` but there's also separate variables for each of the mins and maxes. Is there a reason for this?

**Comment by m-squared96** [comment]
Simply for ease of access. 'axes limits' is specified separately for use in the PSP constructor, whereas the individual limits are also specified for use in MW.init_ui() to increase clarity, which was partially the point of the dictionary approach in the first place. 

IMO, `setup_dict["xmin"]` makes more sense than `setup_dict["axes_limits"][0][0]` when the extra weight to enable this is negligible.

**Comment by m-squared96** [comment]
Closing following merge of features/iss27-defaults into dev. If we want to address the structure of the dictionaries another issue should be opened.
