### ISSUE TITLE
Rewrite the whole project in Rust

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#31]
It's safer than C++ :smiling_imp:

**Comment by m-squared96** [comment]
Yeah no bother. You write the RK4 solvers in Rust and see how sane you are afterwards :laughing:

**Comment by WalJT** [comment]
![image](https://user-images.githubusercontent.com/50880589/64031202-d6e1a100-cb3f-11e9-8b17-3d3f4b4ba3fb.png)

**Comment by WalJT** [comment]
![image](https://user-images.githubusercontent.com/50880589/64031271-f973ba00-cb3f-11e9-9114-e5221c4d4d7d.png)

**Comment by m-squared96** [comment]
Closing for now, but I think @WalJT  this could be your job for a V2 release...
