### ISSUE TITLE
Computation limits of trajectories not always exceeding axes limits

### ISSUE THREAD

**Issue by m-squared96** [m-squared96/PyPLANE#32]
Trajectory computation can sometimes stop short of axes limits, leaving selected trajectories sometimes incomplete in the quiver plot FOV. 

A simple fix would be to simply increase the number of computation steps, but this could lead to memory issues and should be a last resort. Instead, a better way would be to identify trajectories that are likely to continue in a fairly linear manner (i.e. not limit cycles, spirals , etc.) and ensure that the computation limits are sufficient to at least compute the trajectory beyond the limits of the FOV.

**Comment by m-squared96** [comment]
@mjancen is there a way that we can detect circular, inwardly-spiralling..etc. trajectories without needing to implement linearisation beforehand?

A solution I'm thinking of is something along the lines of checking if the trajectory is expected to leave the FOV in a given direction, which would involve checking for spirals, limit cycles, etc., and then checking if it has done so if required. If it should have extended beyond the FOV and hasn't, then advance in whatever time direction is required until it does so. 

Thoughts?

**Comment by mjancen** [comment]
I think increasing the integration time limit would be a simple and sufficient solution for this issue. Unless there are any objections, I will just resolve it in that way.

**Comment by m-squared96** [comment]
That should be fine for now, but we should be able to develop a more sophisticated solution in time. So I say go ahead, but IMO it shouldn't be a permanent solution.

**Comment by mjancen** [comment]
I just don't think it's an interesting problem at the moment, I'd like to implement other features first and maybe come back to this later. Change has been merged, closing this for now.
