### ISSUE TITLE
Do we need the DefaultCanvas class?

### ISSUE THREAD

**Issue by m-squared96** [m-squared96/PyPLANE#33]
I understand the need for a set of default settings to be accessible, but I'm not sure if that warrants the creation of a new class that inherits PSP and does not add any new methods. It seems an unnecessary layer of abstraction.

**Comment by WalJT** [comment]
You could be right... the main reason I did this was to have some place to store the default system outside of the main UI code. I haven't exactly been consistent (some things like text box default values are still defined in ui_main_window.py).

**Comment by m-squared96** [comment]
We should have a look into removing it then. A centralised 'defaults' file is probably the best route, as per issue #27

**Comment by m-squared96** [comment]
Closing this issue, Julian removed the ui_default_canvas.py file.
