### ISSUE TITLE
PhaseSpacePlotter should be split by number of system dimensions

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#41]
I think it might be a good idea to split the PSP into different PSPs that handle each number of dimensions separately. In this way, we could have a switch at the GUI level that chooses the number of dimensions in the system to be plotted, and then the relevant PSP can chosen. At the moment all of the conditional logic relating to what to do based on number of dimensions, which is kinda awkward to change or add to because you need to make sure to make changes wherever an action is done based on num of dimensions.

With separate PSPs, you can be sure that the dimensional logic is separated, and it would be easier to change in the future.

**Comment by m-squared96** [comment]
Gonna have a go at this one, I'll implement the backend first and see if I can feed it up through to the GUI
