### ISSUE TITLE
Add gallery of system of equations

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#54]
This gallery can be used as the set of systems of equations that have been tested for version 0.1. We can use this issue to agree upon which sets of equations with which to test the application.

**Comment by m-squared96** [comment]
Sorry for taking so long to get back to this.

Some example systems I think should be included in the gallery:
1. Logistic/Population growth equation or some more complex example (i.e. budworm outbreak example)
2. Laser threshold modelling (Milonni & Eberly (simpler) or Maxwell-Bloch (more complex))
3. Pendulum/Bead on a wire examples -> showcases catastrophe and/or bifurcation
4. Epidemiological modelling -> topical (lol) pg 91 Strogatz
5. Liapunov orbits
6. Lotka-Volterra systems
7. Relativistic planetary orbits
8. van der Pol oscillators
9. Brusselator chemical oscillator
10. Lorenz systems
