### ISSUE TITLE
PhasePlotter: larger quiver_expansion_factor spaces out arrows more

### ISSUE THREAD

**Issue by mjancen** [m-squared96/PyPLANE#7]
Since the number of points in the (x, y) meshgrid is currently hard-coded to 15, the arrows in the quiver plot space out more as you increase the quiver_expansion_factor attribute. I think that there should be some other attribute that sets the density of the arrows in the plot, so that it's not affected by quiver_expansion_factor.

**Comment by m-squared96** [comment]
Merged branch bug/iss007_qef into dev
